apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
      name: nginx-system
- apiVersion: v1
  kind: Namespace
  metadata:
      name: external-secrets
- apiVersion: v1
  kind: Namespace
  metadata:
      name: pihole-system
- apiVersion: v1
  kind: Namespace
  metadata:
      name: argo-cd
- apiVersion: v1
  kind: Namespace
  metadata:
      name: storage
# - apiVersion: v1
#   kind: Namespace
#   metadata:
#       name: longhorn-system
- apiVersion: v1
  kind: Namespace
  metadata:
      name: clamav
# - apiVersion: v1
#   kind: Namespace
#   metadata:
#       name: trivy-operator
- apiVersion: v1
  kind: Namespace
  metadata:
      name: tailscale-operator
- apiVersion: v1
  kind: Namespace
  metadata:
      name: harbor

