global:
  nodeSelector: {}

replicaCount: 1

revisionHistoryLimit: 4

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent

installCRDs: true
crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
  createPushSecret: true
  conversion:
    enabled: true

controllerClass: ""

processClusterExternalSecret: true

processClusterStore: true

processPushSecret: true

createOperator: true

concurrent: 1
log:
  level: info
  timeEncoding: epoch
service:

rbac:
  # -- Specifies whether role and rolebinding resources should be created.
  create: true

  servicebindings:
    # -- Specifies whether a clusterrole to give servicebindings read access should be created.
    create: true
service:
  # -- Set the ip family policy to configure dual-stack see [Configure dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services)
  ipFamilyPolicy: ""
  # -- Sets the families that should be supported and the order in which they should be applied to ClusterIP as well. Can be IPv4 and/or IPv6.
  ipFamilies: []

certController:
  create: true
  requeueInterval: "5m"
  replicaCount: 1
  revisionHistoryLimit: 5
dnsPolicy: ClusterFirst
