openebs-crds:
  csi:
    volumeSnapshots:
      enabled: true
      keep: true

# Refer to https://github.com/openebs/dynamic-localpv-provisioner/blob/HEAD/deploy/helm/charts/values.yaml for complete set of values.
localpv-provisioner:
  rbac:
    create: true
  localpv:
    basePath: "/data"
    nodeSelector:
      kubernetes.io/hostname: "thoth"
  serviceAccount:
    create: true
  helperPod:
    image:
      registry: ""
      repository: openebs/linux-utils
      pullPolicy: IfNotPresent
      tag: 4.1.0
  analytics:
     enabled: true
     pingInterval: "24h"
# Refer to https://github.com/openebs/zfs-localpv/blob/v2.6.2/deploy/helm/charts/values.yaml for complete set of values.
zfs-localpv:
  crds:
    zfsLocalPv:
      enabled: false
    csi:
      volumeSnapshots:
        enabled: false
  
# Refer to https://github.com/openebs/lvm-localpv/blob/lvm-localpv-1.6.2/deploy/helm/charts/values.yaml for complete set of values.
lvm-localpv:
  storageCapacity: true
  lvmNode:
    nodeSelector:
      kubernetes.io/hostname: "bastet"
  lvmController:
    nodeSelector:
      kubernetes.io/hostname: "anubis"
  serviceAccount:
    lvmController:
      create: true
      name: openebs-lvm-controller-sa
    lvmNode:
      create: true
      name: openebs-lvm-node-sa
  analytics:
    enabled: true
  crds:
    lvmLocalPv:
      enabled: true
    csi:
      volumeSnapshots:
        enabled: true
        keep: true

# Refer to https://github.com/openebs/mayastor-extensions/blob/v2.7.1/chart/values.yaml for complete set of values.
mayastor:
  csi:
    node:
      initContainers:
        enabled: true
  etcd:
    # -- Kubernetes Cluster Domain
    clusterDomain: cluster.local
  localpv-provisioner:
    enabled: false
  crds:
    enabled: true
    csi:
      volumeSnapshots:
        enabled: true
  nodeSelector:
    kubernetes.io/hostname: "horus"
  metrics:
    enabled: true

preUpgradeHook:
  image:
    registry: docker.io
    repo: bitnami/kubectl
    tag: "1.25.15"
    pullPolicy: IfNotPresent

engines:
  local:
    lvm:
      enabled: true
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: true
