repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: argo-cd
    url: https://argoproj.github.io/argo-helm
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: emberstack
    url: https://emberstack.github.io/helm-charts
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: jetstack
    url: https://charts.jetstack.io
  - name: kube-prometheus-stack
    url: https://prometheus-community.github.io/helm-charts
  - name: trivy-operator
    url: https://aquasecurity.github.io/helm-charts/
  - name: tailscale-operator
    url: https://pkgs.tailscale.com/helmcharts
  - name: clamav
    url: https://wiremind.github.io/wiremind-helm-charts

---
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.15.3
    values:
     - ./values/values-cert-manager.yaml
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.8
  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2
    values:
     - ./values/nginx-internal.values.yaml
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
     - ./values/pihole.values.yaml
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    values:
     - ./values/values-external-secrets.yaml
  - name: argo-cd
    chart: argo-cd/argo-cd
    version: 7.6.8
    namespace: argo-cd
    values:
     - ./values/values-argo-cd.yaml
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.0.1
    values:
     - ./values/externaldns.values.yaml
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1
    values:
      - ./values/values-longhorn.yaml
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    version: 66.2.1
    values:
      - ./values/values-kube-prometheus-stack.yaml
  - name: trivy-operator
    namespace: trivy-operator
    chart: trivy-operator/trivy-operator
    version: 0.24.1
    values:
      - ./values/values-trivy-operator.yaml
  - name: tailscale-operator
    namespace: tailscale-operator
    chart: tailscale-operator
    version: 1.70.0
    values:
      - ./values/values-tailscale-operator.yaml
  - name: clamav
    namespace: clamav
    chart: clamav
    version: 3.2.0
    values:
      - ./values/values-clamav.yaml

helmDefaults:
  cleanupOnFail: true
  verify: false
  historyMax: 5
